/*
Main program of calculator example.
Simply invoke the parser generated by bison, and then display the output.
*/

#include <stdio.h>
#include <string.h>
#include "expr.h"
#include "stmt.h"
#include "scope.h"
#include "param_list.h"
#include "type.h"
#include "decl.h"

/* Clunky: Declare the parse function generated from parser.bison */
extern int yyparse();
extern FILE *yyin;
extern char *yytext;

/* Clunky: Declare the result of the parser from parser.bison */
extern struct decl *parser_result;


int main( int argv, char *argc[] )
{
	//yyin = fopen(argc[1],"r");
	if(!strcmp(argc[1],"-print")){
		yyin = fopen(argc[2],"r");
		if(yyparse()==0) {
			decl_print(parser_result,0);
			scope_enter();
			return 0;
		}
	}else if(!strcmp(argc[1],"-resolve"))
		{
			yyin = fopen(argc[2],"r");
			if(yyparse()==0) {
				scope_enter();
				decl_resolve(parser_result,1);
				printf("%d resolve errors found\n",get_incrementError(3));
				if(get_incrementError(3) > 0)return 0;
				return 1;
			}	
		}
	else if(!strcmp(argc[1],"-typecheck"))
		{
			yyin = fopen(argc[2],"r");
			if(yyparse()==0) {
				scope_enter();
				decl_resolve(parser_result,0);
				if(get_incrementError(3) > 0){
					printf("Resolve Errors Founded, type Check Aborted\n");
					return 0;
				}
				decl_typecheck(parser_result);
				return 1;
			}	
		}
	else if(!strcmp(argc[1],"-codegen")){
		yyin = fopen(argc[2],"r");
			if(yyparse()==0) {
				scope_enter();
				decl_resolve(parser_result,0);
				if(get_incrementError(3) > 0){
					printf("Resolve Errors Founded, type Check Aborted\n");
					return 0;
				}
				else printf("No resolve errors\n");
				decl_typecheck(parser_result);
				printf("%d typeckek errors found\n",get_incrementError(4));
				if(get_incrementError(4) > 0)return 0;
				FILE * fp;
   				fp = fopen (argc[3], "w+");
				decl_codegen(parser_result,fp);
				return 1;
			}	

	}
 

  return 1;
}

