#ifndef lint
static const char yysccsid[] = "@(#)yaccpar	1.9 (Berkeley) 02/21/93";
#endif

#include <stdlib.h>
#include <string.h>

#define YYBYACC 1
#define YYMAJOR 1
#define YYMINOR 9
#define YYPATCH 20070509

#define YYEMPTY (-1)
#define yyclearin    (yychar = YYEMPTY)
#define yyerrok      (yyerrflag = 0)
#define YYRECOVERING (yyerrflag != 0)

extern int yyparse(void);

static int yygrowstack(void);
#define YYPREFIX "yy"
#line 59 "grammar.bison"
typedef union {
	struct decl *decl;
	struct stmt *stmt;
	struct expr *expr;
	struct param_list *param_list;
	struct type *type;
	char *c;
} YYSTYPE;
#line 75 "grammar.bison"
#include <math.h>
#include <stdio.h>
#include <string.h>
#include "expr.h"
#include "type.h"
#include "param_list.h"
#include "decl.h"
#include "stmt.h"

/*
YYSTYPE is the lexical value returned by each rule in a bison grammar.
By default, it is an integer. In this example, we are returning a pointer to an expression.
*/
/*
Clunky: Manually declare the interface to the scanner generated by flex. 
*/

extern char *yytext;
extern int yylex();
extern int yyerror( char *str );

/*
Clunky: Keep the final result of the parse in a global variable,
so that it can be retrieved by main().
*/

struct decl *parser_result = 0;


#line 62 "parser.tab.c"
#define TOKEN_UNARY_NEGATION 257
#define TOKEN_STRING 258
#define TOKEN_INTEGER 259
#define TOKEN_CHAR 260
#define TOKEN_DO 261
#define TOKEN_FALSE 262
#define TOKEN_WHILE 263
#define TOKEN_IF 264
#define TOKEN_ELSE 265
#define TOKEN_ARRAY 266
#define TOKEN_BOOLEAN 267
#define TOKEN_FOR 268
#define TOKEN_FUNCTION 269
#define TOKEN_PRINT 270
#define TOKEN_RETURN 271
#define TOKEN_STRING_LITERAL 272
#define TOKEN_CHARACTER_LITERAL 273
#define TOKEN_INTEGER_LITERAL 274
#define TOKEN_TRUE 275
#define TOKEN_VOID 276
#define TOKEN_IDENTIFIER 277
#define TOKEN_SCOLON 278
#define TOKEN_GE 279
#define TOKEN_LE 280
#define TOKEN_GT 281
#define TOKEN_LT 282
#define TOKEN_OR 283
#define TOKEN_AND 284
#define TOKEN_NOT 285
#define TOKEN_EQ 286
#define TOKEN_NE 287
#define TOKEN_INCREMENT 288
#define TOKEN_DECREMENT 289
#define TOKEN_ADD 290
#define TOKEN_SUB 291
#define TOKEN_MULT 292
#define TOKEN_DIV 293
#define TOKEN_NEG 294
#define TOKEN_ASSIGN 295
#define TOKEN_EXPONENTIATION 296
#define TOKEN_MOD 297
#define TOKEN_COLON 298
#define TOKEN_COMMA 299
#define TOKEN_OPPAR 300
#define TOKEN_CLPAR 301
#define TOKEN_OPBRAK 302
#define TOKEN_CLBRAK 303
#define TOKEN_OPBRACE 304
#define TOKEN_CLBRACE 305
#define YYERRCODE 256
short yylhs[] = {                                        -1,
    0,    1,    1,    2,    2,    2,    2,   27,   27,   27,
   27,   27,   27,   27,   28,   28,   28,   28,   28,   28,
   28,   24,   24,   25,   25,   26,    8,    8,   21,   20,
   20,   29,    3,    3,    3,    3,    3,    3,    3,    3,
    5,    5,    5,    5,    5,    5,    5,    4,    4,    6,
    6,    7,   19,   19,   17,   17,   11,   11,   10,   10,
   22,   22,   22,   22,   22,   22,   22,   14,   14,   14,
   16,   16,   16,   16,   13,   13,   12,   12,   12,   23,
   23,   23,    9,    9,   18,   18,   18,   18,   18,   18,
   18,   18,   18,   15,   15,
};
short yylen[] = {                                         2,
    1,    2,    0,    6,    9,    4,    7,    1,    1,    1,
    1,    5,    5,    1,    1,    1,    1,    1,    5,    5,
    1,    0,    1,    3,    1,    5,    0,    1,    1,    3,
    1,    1,    1,    2,    9,    3,    7,    5,    3,    3,
    7,    3,    3,    3,    2,    1,    9,    0,    1,    1,
    1,    2,    0,    1,    1,    3,    3,    1,    3,    1,
    3,    3,    3,    3,    3,    3,    1,    3,    3,    1,
    3,    3,    3,    1,    3,    1,    2,    2,    1,    2,
    2,    1,    1,    3,    1,    5,    4,    1,    1,    1,
    1,    1,    3,    4,    0,
};
short yydefred[] = {                                      0,
   32,    0,    1,    0,    0,    2,    0,    8,    9,   10,
    0,   11,    0,   14,    0,    0,   15,   16,   17,    0,
   18,    0,   21,    0,    6,    0,   92,   89,   90,   88,
   91,    0,    0,    0,    0,    0,    0,    0,    0,   76,
    0,    0,    0,    0,   83,    0,   79,    0,    0,    0,
    0,    0,    0,    0,   77,   78,    0,    0,    0,   29,
    0,   80,   81,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,   23,   25,    0,    0,
    0,    0,    0,    0,   33,    0,    0,   49,   51,    0,
    0,    4,   84,    0,    0,   93,    0,    0,   75,    0,
    0,    0,    0,    0,    0,   12,    0,    0,    0,    0,
    0,    0,    0,   28,    0,    0,    0,   13,    0,    0,
    0,    0,    0,    0,   52,    0,    7,   34,    0,   30,
   87,    0,   19,   20,    0,    0,    0,   40,   39,   36,
    5,    0,   86,    0,    0,    0,    0,   26,    0,    0,
    0,    0,    0,    0,   38,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,   94,    0,    0,
    0,    0,    0,   37,    0,    0,    0,    0,    0,    0,
   35,    0,    0,   41,    0,    0,   47,
};
short yydgoto[] = {                                       2,
    3,   95,   96,   97,  166,   98,   99,  123,   37,   38,
   39,   40,   41,   42,  153,   43,   82,   45,   83,   60,
   61,   46,   47,   86,   87,   88,   15,   24,   48,
};
short yysindex[] = {                                   -259,
    0,    0,    0, -259, -289,    0,  647,    0,    0,    0,
 -260,    0,  651,    0, -265, -155,    0,    0,    0, -222,
    0,  666,    0, -197,    0,   69,    0,    0,    0,    0,
    0, -226, -226,   89,  651,   89, -219, -173, -156,    0,
 -153, -140, -119, -264,    0,   97,    0, -281,   89, -137,
 -154, -259,   26, -234,    0,    0, -196, -141, -216,    0,
 -130,    0,    0,   89,   89,   89,   89,   89,   89,   89,
   89,   89,  666,   89,   89,   89,   89,   89,   89,   89,
   89, -127, -126,   89, -259, -118,    0,    0, -116, -105,
 -104,   89,   89,   26,    0,   26, -100,    0,    0, -207,
 -174,    0,    0,   89,   89,    0,   97, -173,    0, -119,
 -119, -153, -153, -153, -156,    0, -140, -140, -140, -140,
 -140, -140, -101,    0, -263,  651,  -87,    0,  651,   89,
   89,  -62,  -60,  -86,    0, -218,    0,    0, -206,    0,
    0,  -78,    0,    0,  -98, -148,  -51,    0,    0,    0,
    0,   89,    0, -259,   48,   89, -202,    0,  -66,  -54,
   89,   89,   26,    0,    0,  -18, -193,  -22,  -78,   89,
   89,  -19,  -17,  -45,   26,    0,   89,    0, -132,  -11,
    0,    0,    0,    0,  -37,   48,   89,   26,    5,   -5,
    0,   48,   89,    0,  -15,   48,    0,
};
short yyrindex[] = {                                    282,
    0,    0,    0,  282,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,  172,  -92, -237,    0,
  228,  424,  340,    0,    0,   54,    0,  116,  -16,    0,
    0,  -10,  -13,    0,    0,    0,    0,    0, -267,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,    0,    0,    0,    0,   -8,
    0, -268,    0,    0,  -10,    0,    0,    0,    0,    0,
    0,   24,   27,  -13,    0,    8,    0,    0,    0,    9,
  200,    0,    0,    0,    0,    0,   87,  599,    0,  368,
  396,  256,  284,  312,  -93,    0,  452,  480,  508,  536,
  564,  592,    0,    0,    0,    0,    0,    0,    0,    0,
   27,    0,    0,    0,    0,    0,    0,    0,    0,    0,
    0,  144,    0,    0,    6,    0,    0,    0,    0,    0,
    0,    0,    0,    0,    0,   27,    0,    0,    0,    0,
   24,   27,  -13, -248,    0,    0,    0,    0,  144,    0,
   27,    0,    0,    0,    0, -133,   14,    0,    0,    0,
  -42,  -20,    4,    0,    0,    0,   27,    0,    0,    0,
    0,    0,   14,    0,    0,    0,    0,
};
short yygindex[] = {                                      0,
  279,    2,  -88,  -90,  -26,  210,    0,  -85,    0,  259,
  255,  262,   45,  162,  160,   94,   29,    0,  -81,  -77,
    0,  270,  147,  250,  182,    0,  -14,  -35,    1,
};
#define YYTABLESIZE 942
short yytable[] = {                                      58,
    5,    4,  124,  134,    5,    4,  132,   51,    7,   54,
   31,  133,   25,   33,  124,   33,   46,    1,   80,   33,
   81,   33,   33,   33,   33,   33,   33,  140,   33,   26,
   72,   72,   54,   31,   54,   27,   33,   31,   73,  142,
   55,   16,   33,  102,   44,   28,   29,   30,   31,  147,
    1,   33,   89,  101,   54,   33,   33,   55,  116,  138,
   72,   55,   57,   55,   59,   55,  165,   55,   62,   63,
  138,  151,  174,   34,  168,  172,   72,   36,   72,   49,
  173,  100,  105,  124,  176,   89,  184,   72,   72,  180,
  143,  105,   72,  145,  101,  185,  101,  165,   72,  191,
  169,   72,   52,  184,  103,  190,   27,  191,   59,  125,
   64,  195,   44,  112,  113,  114,   28,   29,   30,   31,
   59,    1,  100,    7,  136,   80,   65,   81,   34,   32,
   34,   45,  139,   59,   34,   33,   34,   34,   34,   34,
   34,   34,   66,   34,   34,   85,   72,   35,   36,   67,
   68,   34,  155,  104,   89,  101,  164,   34,  146,  189,
  110,  111,   72,  101,   84,  194,   34,   72,  186,  197,
   34,   34,   69,   70,  106,  101,  126,   71,   55,   56,
  157,  129,  128,  167,   56,   58,  101,  164,  101,   59,
   58,  100,  101,  164,  130,  131,  101,  164,  179,  141,
  154,   56,   58,  136,  137,   56,   58,   56,   58,   56,
   58,   56,   58,  144,  167,  148,  136,  149,  150,   40,
  167,   40,   43,  152,  167,   40,  156,   40,   40,   40,
   40,   40,   40,  170,   40,  117,  118,  119,  120,  121,
  122,   39,   40,   39,   42,  171,  175,   39,   40,   39,
   39,   39,   39,   39,   39,  177,   39,   40,  181,  183,
  182,   40,   40,  188,   39,   36,  187,   36,   44,  192,
   39,   36,  193,   36,   36,   36,   36,   36,   36,   39,
   36,    3,    6,   39,   39,  196,   53,   27,   36,   90,
   22,   48,   27,   91,   36,   92,   93,   28,   29,   30,
   31,   27,    1,   36,   53,  135,   24,   36,   36,   27,
   32,  159,   50,   31,   53,  160,   33,  161,  162,   28,
   29,   30,   31,  108,    1,   34,  115,  109,  178,   94,
   27,   60,   32,  107,  127,  158,   60,   60,   33,    0,
   28,   29,   30,   31,    0,    1,    0,   34,   60,    0,
   27,  163,   60,   32,   60,    0,   60,    0,   60,   33,
   28,   29,   30,   31,   59,    1,    0,    0,   34,   59,
   59,    0,   53,   32,    0,   74,   75,   76,   77,   33,
    0,   59,   78,   79,    0,   59,    0,   59,   34,   59,
    0,   59,   36,   85,   85,   85,   85,   85,   85,   85,
    0,   85,   85,   85,   85,   85,   85,   85,   85,    0,
   85,   85,   85,    0,   85,    0,   85,    0,   85,    0,
   85,   95,   95,   95,   95,   95,   95,   95,    0,   95,
   95,   95,   95,   95,   95,   95,   95,    0,   95,   95,
   95,    0,   95,    0,   95,    0,   95,    0,   95,   82,
   82,   82,   82,   82,   82,   82,    0,   82,   82,    0,
    0,   82,   82,   82,   82,    0,   82,   82,   82,    0,
   82,    0,   82,    0,   82,    0,   82,   85,   85,   85,
   85,   85,   85,   85,    0,   85,   85,   85,   85,   85,
   85,   85,   85,    0,   85,   85,   85,    0,   85,    0,
    0,    0,    0,    0,   85,   74,   74,   74,   74,   74,
   74,   74,    0,   74,   74,    0,    0,   74,   74,   74,
   74,    0,   74,    0,   74,    0,   74,    0,   74,    0,
   74,    0,   74,   71,   71,   71,   71,   71,   71,   71,
    0,   71,   71,    0,    0,   71,   71,   71,   71,    0,
   71,    0,   71,    0,   71,    0,   71,    0,   71,    0,
   71,   72,   72,   72,   72,   72,   72,   72,    0,   72,
   72,    0,    0,   72,   72,   72,   72,    0,   72,    0,
   72,    0,   72,    0,   72,    0,   72,    0,   72,   73,
   73,   73,   73,   73,   73,   73,    0,   73,   73,    0,
    0,   73,   73,   73,   73,    0,   73,    0,   73,    0,
   73,    0,   73,    0,   73,    0,   73,   70,   70,   70,
   70,   70,   70,   70,    0,   70,   70,    0,    0,   70,
   70,    0,    0,    0,   70,    0,    0,    0,   70,    0,
   70,    0,   70,    0,   70,   68,   68,   68,   68,   68,
   68,   68,    0,   68,   68,    0,    0,   68,   68,    0,
    0,    0,   68,    0,    0,    0,   68,    0,   68,    0,
   68,    0,   68,   69,   69,   69,   69,   69,   69,   69,
    0,   69,   69,    0,    0,   69,   69,    0,    0,    0,
   69,    0,    0,    0,   69,    0,   69,    0,   69,    0,
   69,   67,   67,   67,   67,   67,   67,   67,    0,   67,
   67,    0,    0,    0,    0,    0,    0,    0,   67,    0,
    0,    0,   67,    0,   67,    0,   67,    0,   67,   61,
   61,   61,   61,   61,   61,   61,    0,   61,   61,    0,
    0,    0,    0,    0,    0,    0,   61,    0,    0,    0,
   61,    0,   61,    0,   61,    0,   61,   63,   63,   63,
   63,   63,   63,   63,    0,   63,   63,    0,    0,    0,
    0,    0,    0,    0,   63,    0,    0,    0,   63,    0,
   63,    0,   63,    0,   63,   62,   62,   62,   62,   62,
   62,   62,    0,   62,   62,    0,    0,    0,    0,    0,
    0,    0,   62,    0,    0,    0,   62,    0,   62,    0,
   62,    0,   62,   64,   64,   64,   64,   64,   64,   64,
    0,   64,   64,    0,    0,    0,    0,    0,    0,    0,
   64,    0,    0,    0,   64,    0,   64,    0,   64,    0,
   64,   66,   66,   66,   66,   66,   66,   66,    0,   66,
   66,    0,    0,    0,    0,    0,    0,    0,   66,    0,
    0,    0,   66,    0,   66,    0,   66,    0,   66,   65,
   65,   65,   65,   65,   65,   65,   57,   65,   65,    0,
    0,   57,    0,    0,    0,    0,   65,    0,    0,    0,
   65,    0,   65,   57,   65,    0,   65,   57,    0,   57,
    0,   57,    0,   57,    8,    9,   10,    0,   17,   18,
   19,    0,   11,   12,    0,   13,   20,   21,    0,   22,
    0,    0,   14,    8,    9,   10,   23,    0,    0,    0,
    0,   50,   12,    0,   13,    0,    0,    0,    0,    0,
    0,   14,
};
short yycheck[] = {                                      35,
    0,    0,   80,   94,    4,    4,   92,   22,  298,  278,
  278,   93,  278,  262,   92,  264,  265,  277,  300,  268,
  302,  270,  271,  272,  273,  274,  275,  105,  277,  295,
  295,  295,  301,  301,  303,  262,  285,  305,  303,  303,
  278,  302,  291,  278,   16,  272,  273,  274,  275,  131,
  277,  300,   52,   53,   26,  304,  305,  295,   73,  278,
  295,  299,   34,  301,   36,  303,  155,  305,  288,  289,
  278,  278,  163,  300,  156,  161,  295,  304,  295,  302,
  162,   53,  299,  161,  278,   85,  175,  295,  295,  171,
  126,  299,  295,  129,   94,  177,   96,  186,  295,  188,
  303,  295,  300,  192,  301,  187,  262,  196,   80,   81,
  284,  193,   84,   69,   70,   71,  272,  273,  274,  275,
   92,  277,   94,  298,   96,  300,  283,  302,  262,  285,
  264,  265,  104,  105,  268,  291,  270,  271,  272,  273,
  274,  275,  296,  277,  300,  300,  295,  303,  304,  290,
  291,  285,  301,  295,  154,  155,  155,  291,  130,  186,
   67,   68,  295,  163,  302,  192,  300,  295,  301,  196,
  304,  305,  292,  293,  305,  175,  303,  297,   32,   33,
  152,  298,  301,  155,  278,  278,  186,  186,  188,  161,
  283,  163,  192,  192,  300,  300,  196,  196,  170,  301,
  299,  295,  295,  175,  305,  299,  299,  301,  301,  303,
  303,  305,  305,  301,  186,  278,  188,  278,  305,  262,
  192,  264,  265,  302,  196,  268,  278,  270,  271,  272,
  273,  274,  275,  300,  277,   74,   75,   76,   77,   78,
   79,  262,  285,  264,  265,  300,  265,  268,  291,  270,
  271,  272,  273,  274,  275,  278,  277,  300,  278,  305,
  278,  304,  305,  301,  285,  262,  278,  264,  265,  265,
  291,  268,  278,  270,  271,  272,  273,  274,  275,  300,
  277,    0,    4,  304,  305,  301,  303,  262,  285,  264,
  301,  305,  301,  268,  291,  270,  271,  272,  273,  274,
  275,  278,  277,  300,  278,   96,  301,  304,  305,  262,
  285,  264,  305,  305,  301,  268,  291,  270,  271,  272,
  273,  274,  275,   65,  277,  300,   72,   66,  169,  304,
  262,  278,  285,   64,   85,  154,  283,  284,  291,   -1,
  272,  273,  274,  275,   -1,  277,   -1,  300,  295,   -1,
  262,  304,  299,  285,  301,   -1,  303,   -1,  305,  291,
  272,  273,  274,  275,  278,  277,   -1,   -1,  300,  283,
  284,   -1,  304,  285,   -1,  279,  280,  281,  282,  291,
   -1,  295,  286,  287,   -1,  299,   -1,  301,  300,  303,
   -1,  305,  304,  278,  279,  280,  281,  282,  283,  284,
   -1,  286,  287,  288,  289,  290,  291,  292,  293,   -1,
  295,  296,  297,   -1,  299,   -1,  301,   -1,  303,   -1,
  305,  278,  279,  280,  281,  282,  283,  284,   -1,  286,
  287,  288,  289,  290,  291,  292,  293,   -1,  295,  296,
  297,   -1,  299,   -1,  301,   -1,  303,   -1,  305,  278,
  279,  280,  281,  282,  283,  284,   -1,  286,  287,   -1,
   -1,  290,  291,  292,  293,   -1,  295,  296,  297,   -1,
  299,   -1,  301,   -1,  303,   -1,  305,  278,  279,  280,
  281,  282,  283,  284,   -1,  286,  287,  288,  289,  290,
  291,  292,  293,   -1,  295,  296,  297,   -1,  299,   -1,
   -1,   -1,   -1,   -1,  305,  278,  279,  280,  281,  282,
  283,  284,   -1,  286,  287,   -1,   -1,  290,  291,  292,
  293,   -1,  295,   -1,  297,   -1,  299,   -1,  301,   -1,
  303,   -1,  305,  278,  279,  280,  281,  282,  283,  284,
   -1,  286,  287,   -1,   -1,  290,  291,  292,  293,   -1,
  295,   -1,  297,   -1,  299,   -1,  301,   -1,  303,   -1,
  305,  278,  279,  280,  281,  282,  283,  284,   -1,  286,
  287,   -1,   -1,  290,  291,  292,  293,   -1,  295,   -1,
  297,   -1,  299,   -1,  301,   -1,  303,   -1,  305,  278,
  279,  280,  281,  282,  283,  284,   -1,  286,  287,   -1,
   -1,  290,  291,  292,  293,   -1,  295,   -1,  297,   -1,
  299,   -1,  301,   -1,  303,   -1,  305,  278,  279,  280,
  281,  282,  283,  284,   -1,  286,  287,   -1,   -1,  290,
  291,   -1,   -1,   -1,  295,   -1,   -1,   -1,  299,   -1,
  301,   -1,  303,   -1,  305,  278,  279,  280,  281,  282,
  283,  284,   -1,  286,  287,   -1,   -1,  290,  291,   -1,
   -1,   -1,  295,   -1,   -1,   -1,  299,   -1,  301,   -1,
  303,   -1,  305,  278,  279,  280,  281,  282,  283,  284,
   -1,  286,  287,   -1,   -1,  290,  291,   -1,   -1,   -1,
  295,   -1,   -1,   -1,  299,   -1,  301,   -1,  303,   -1,
  305,  278,  279,  280,  281,  282,  283,  284,   -1,  286,
  287,   -1,   -1,   -1,   -1,   -1,   -1,   -1,  295,   -1,
   -1,   -1,  299,   -1,  301,   -1,  303,   -1,  305,  278,
  279,  280,  281,  282,  283,  284,   -1,  286,  287,   -1,
   -1,   -1,   -1,   -1,   -1,   -1,  295,   -1,   -1,   -1,
  299,   -1,  301,   -1,  303,   -1,  305,  278,  279,  280,
  281,  282,  283,  284,   -1,  286,  287,   -1,   -1,   -1,
   -1,   -1,   -1,   -1,  295,   -1,   -1,   -1,  299,   -1,
  301,   -1,  303,   -1,  305,  278,  279,  280,  281,  282,
  283,  284,   -1,  286,  287,   -1,   -1,   -1,   -1,   -1,
   -1,   -1,  295,   -1,   -1,   -1,  299,   -1,  301,   -1,
  303,   -1,  305,  278,  279,  280,  281,  282,  283,  284,
   -1,  286,  287,   -1,   -1,   -1,   -1,   -1,   -1,   -1,
  295,   -1,   -1,   -1,  299,   -1,  301,   -1,  303,   -1,
  305,  278,  279,  280,  281,  282,  283,  284,   -1,  286,
  287,   -1,   -1,   -1,   -1,   -1,   -1,   -1,  295,   -1,
   -1,   -1,  299,   -1,  301,   -1,  303,   -1,  305,  278,
  279,  280,  281,  282,  283,  284,  278,  286,  287,   -1,
   -1,  283,   -1,   -1,   -1,   -1,  295,   -1,   -1,   -1,
  299,   -1,  301,  295,  303,   -1,  305,  299,   -1,  301,
   -1,  303,   -1,  305,  258,  259,  260,   -1,  258,  259,
  260,   -1,  266,  267,   -1,  269,  266,  267,   -1,  269,
   -1,   -1,  276,  258,  259,  260,  276,   -1,   -1,   -1,
   -1,  266,  267,   -1,  269,   -1,   -1,   -1,   -1,   -1,
   -1,  276,
};
#define YYFINAL 2
#ifndef YYDEBUG
#define YYDEBUG 0
#endif
#define YYMAXTOKEN 305
#if YYDEBUG
char *yyname[] = {
"end-of-file",0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,"TOKEN_UNARY_NEGATION",
"TOKEN_STRING","TOKEN_INTEGER","TOKEN_CHAR","TOKEN_DO","TOKEN_FALSE",
"TOKEN_WHILE","TOKEN_IF","TOKEN_ELSE","TOKEN_ARRAY","TOKEN_BOOLEAN","TOKEN_FOR",
"TOKEN_FUNCTION","TOKEN_PRINT","TOKEN_RETURN","TOKEN_STRING_LITERAL",
"TOKEN_CHARACTER_LITERAL","TOKEN_INTEGER_LITERAL","TOKEN_TRUE","TOKEN_VOID",
"TOKEN_IDENTIFIER","TOKEN_SCOLON","TOKEN_GE","TOKEN_LE","TOKEN_GT","TOKEN_LT",
"TOKEN_OR","TOKEN_AND","TOKEN_NOT","TOKEN_EQ","TOKEN_NE","TOKEN_INCREMENT",
"TOKEN_DECREMENT","TOKEN_ADD","TOKEN_SUB","TOKEN_MULT","TOKEN_DIV","TOKEN_NEG",
"TOKEN_ASSIGN","TOKEN_EXPONENTIATION","TOKEN_MOD","TOKEN_COLON","TOKEN_COMMA",
"TOKEN_OPPAR","TOKEN_CLPAR","TOKEN_OPBRAK","TOKEN_CLBRAK","TOKEN_OPBRACE",
"TOKEN_CLBRACE",
};
char *yyrule[] = {
"$accept : program",
"program : decl_list",
"decl_list : decl decl_list",
"decl_list :",
"decl : ident TOKEN_COLON type TOKEN_ASSIGN expr TOKEN_SCOLON",
"decl : ident TOKEN_COLON TOKEN_ARRAY TOKEN_OPBRAK TOKEN_CLBRAK type2 TOKEN_ASSIGN expr TOKEN_SCOLON",
"decl : ident TOKEN_COLON type TOKEN_SCOLON",
"decl : ident TOKEN_COLON type TOKEN_ASSIGN TOKEN_OPBRACE stmt_list TOKEN_CLBRACE",
"type : TOKEN_STRING",
"type : TOKEN_INTEGER",
"type : TOKEN_CHAR",
"type : TOKEN_BOOLEAN",
"type : TOKEN_ARRAY TOKEN_OPBRAK expr TOKEN_CLBRAK type",
"type : TOKEN_FUNCTION type2 TOKEN_OPPAR param_list TOKEN_CLPAR",
"type : TOKEN_VOID",
"type2 : TOKEN_STRING",
"type2 : TOKEN_INTEGER",
"type2 : TOKEN_CHAR",
"type2 : TOKEN_BOOLEAN",
"type2 : TOKEN_ARRAY TOKEN_OPBRAK op_expr TOKEN_CLBRAK type2",
"type2 : TOKEN_FUNCTION type TOKEN_OPPAR param_list TOKEN_CLPAR",
"type2 : TOKEN_VOID",
"param_list :",
"param_list : not_empty_param_list",
"not_empty_param_list : ident TOKEN_COLON type2",
"not_empty_param_list : param_list2",
"param_list2 : ident TOKEN_COLON type2 TOKEN_COMMA not_empty_param_list",
"expr_list :",
"expr_list : expr_list2",
"expr_list_array : expr_list2",
"expr_list2 : expr TOKEN_COMMA expr_list2",
"expr_list2 : expr",
"ident : TOKEN_IDENTIFIER",
"stmt : decl",
"stmt : expr TOKEN_SCOLON",
"stmt : TOKEN_FOR TOKEN_OPPAR op_expr TOKEN_SCOLON op_expr TOKEN_SCOLON op_expr TOKEN_CLPAR stmt",
"stmt : TOKEN_OPBRACE stmt_list TOKEN_CLBRACE",
"stmt : TOKEN_IF TOKEN_OPPAR expr TOKEN_CLPAR match_stmt TOKEN_ELSE stmt",
"stmt : TOKEN_IF TOKEN_OPPAR expr TOKEN_CLPAR stmt",
"stmt : TOKEN_RETURN op_expr TOKEN_SCOLON",
"stmt : TOKEN_PRINT expr_list TOKEN_SCOLON",
"match_stmt : TOKEN_IF TOKEN_OPPAR expr TOKEN_CLPAR match_stmt TOKEN_ELSE match_stmt",
"match_stmt : TOKEN_RETURN op_expr TOKEN_SCOLON",
"match_stmt : TOKEN_PRINT expr_list TOKEN_SCOLON",
"match_stmt : TOKEN_OPBRACE stmt_list TOKEN_CLBRACE",
"match_stmt : expr TOKEN_SCOLON",
"match_stmt : decl",
"match_stmt : TOKEN_FOR TOKEN_OPPAR op_expr TOKEN_SCOLON op_expr TOKEN_SCOLON op_expr TOKEN_CLPAR match_stmt",
"stmt_list :",
"stmt_list : not_empty_stmt_list",
"not_empty_stmt_list : stmt",
"not_empty_stmt_list : stmt_list2",
"stmt_list2 : stmt not_empty_stmt_list",
"op_expr :",
"op_expr : expr",
"expr : or_expr",
"expr : expr TOKEN_ASSIGN or_expr",
"or_expr : or_expr TOKEN_OR and_expr",
"or_expr : and_expr",
"and_expr : and_expr TOKEN_AND compare_expr",
"and_expr : compare_expr",
"compare_expr : compare_expr TOKEN_GE add_expr",
"compare_expr : compare_expr TOKEN_GT add_expr",
"compare_expr : compare_expr TOKEN_LE add_expr",
"compare_expr : compare_expr TOKEN_LT add_expr",
"compare_expr : compare_expr TOKEN_NE add_expr",
"compare_expr : compare_expr TOKEN_EQ add_expr",
"compare_expr : add_expr",
"add_expr : add_expr TOKEN_ADD mult_expr",
"add_expr : add_expr TOKEN_SUB mult_expr",
"add_expr : mult_expr",
"mult_expr : mult_expr TOKEN_MULT expo_expr",
"mult_expr : mult_expr TOKEN_DIV expo_expr",
"mult_expr : mult_expr TOKEN_MOD expo_expr",
"mult_expr : expo_expr",
"expo_expr : expo_expr TOKEN_EXPONENTIATION unary_expr",
"expo_expr : unary_expr",
"unary_expr : TOKEN_NOT inc_expr",
"unary_expr : TOKEN_SUB inc_expr",
"unary_expr : inc_expr",
"inc_expr : paren TOKEN_INCREMENT",
"inc_expr : paren TOKEN_DECREMENT",
"inc_expr : paren",
"paren : primary_expr",
"paren : TOKEN_OPPAR expr TOKEN_CLPAR",
"primary_expr : ident",
"primary_expr : ident TOKEN_OPBRAK expr TOKEN_CLBRAK array_elements",
"primary_expr : ident TOKEN_OPPAR expr_list TOKEN_CLPAR",
"primary_expr : TOKEN_INTEGER_LITERAL",
"primary_expr : TOKEN_STRING_LITERAL",
"primary_expr : TOKEN_CHARACTER_LITERAL",
"primary_expr : TOKEN_TRUE",
"primary_expr : TOKEN_FALSE",
"primary_expr : TOKEN_OPBRACE expr_list_array TOKEN_CLBRACE",
"array_elements : TOKEN_OPBRAK expr TOKEN_CLBRAK array_elements",
"array_elements :",
};
#endif
#if YYDEBUG
#include <stdio.h>
#endif

/* define the initial stack-sizes */
#ifdef YYSTACKSIZE
#undef YYMAXDEPTH
#define YYMAXDEPTH  YYSTACKSIZE
#else
#ifdef YYMAXDEPTH
#define YYSTACKSIZE YYMAXDEPTH
#else
#define YYSTACKSIZE 10000
#define YYMAXDEPTH  10000
#endif
#endif

#define YYINITSTACKSIZE 500

int      yydebug;
int      yynerrs;
int      yyerrflag;
int      yychar;
short   *yyssp;
YYSTYPE *yyvsp;
YYSTYPE  yyval;
YYSTYPE  yylval;

/* variables for the parser stack */
static short   *yyss;
static short   *yysslim;
static YYSTYPE *yyvs;
static int      yystacksize;
#line 374 "grammar.bison"


//This function will be called by bison if the parse should
//encounter an error.  In principle, "str" will contain something
//useful.  In practice, it often does not.


int yyerror( char *str )
{
	printf("parse error: %s\n",str);
	exit(EXIT_FAILURE );
}
#line 578 "parser.tab.c"
/* allocate initial stack or double stack size, up to YYMAXDEPTH */
static int yygrowstack(void)
{
    int newsize, i;
    short *newss;
    YYSTYPE *newvs;

    if ((newsize = yystacksize) == 0)
        newsize = YYINITSTACKSIZE;
    else if (newsize >= YYMAXDEPTH)
        return -1;
    else if ((newsize *= 2) > YYMAXDEPTH)
        newsize = YYMAXDEPTH;

    i = yyssp - yyss;
    newss = (yyss != 0)
          ? (short *)realloc(yyss, newsize * sizeof(*newss))
          : (short *)malloc(newsize * sizeof(*newss));
    if (newss == 0)
        return -1;

    yyss  = newss;
    yyssp = newss + i;
    newvs = (yyvs != 0)
          ? (YYSTYPE *)realloc(yyvs, newsize * sizeof(*newvs))
          : (YYSTYPE *)malloc(newsize * sizeof(*newvs));
    if (newvs == 0)
        return -1;

    yyvs = newvs;
    yyvsp = newvs + i;
    yystacksize = newsize;
    yysslim = yyss + newsize - 1;
    return 0;
}

#define YYABORT goto yyabort
#define YYREJECT goto yyabort
#define YYACCEPT goto yyaccept
#define YYERROR goto yyerrlab
int
yyparse(void)
{
    register int yym, yyn, yystate;
#if YYDEBUG
    register const char *yys;

    if ((yys = getenv("YYDEBUG")) != 0)
    {
        yyn = *yys;
        if (yyn >= '0' && yyn <= '9')
            yydebug = yyn - '0';
    }
#endif

    yynerrs = 0;
    yyerrflag = 0;
    yychar = YYEMPTY;

    if (yyss == NULL && yygrowstack()) goto yyoverflow;
    yyssp = yyss;
    yyvsp = yyvs;
    *yyssp = yystate = 0;

yyloop:
    if ((yyn = yydefred[yystate]) != 0) goto yyreduce;
    if (yychar < 0)
    {
        if ((yychar = yylex()) < 0) yychar = 0;
#if YYDEBUG
        if (yydebug)
        {
            yys = 0;
            if (yychar <= YYMAXTOKEN) yys = yyname[yychar];
            if (!yys) yys = "illegal-symbol";
            printf("%sdebug: state %d, reading %d (%s)\n",
                    YYPREFIX, yystate, yychar, yys);
        }
#endif
    }
    if ((yyn = yysindex[yystate]) && (yyn += yychar) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yychar)
    {
#if YYDEBUG
        if (yydebug)
            printf("%sdebug: state %d, shifting to state %d\n",
                    YYPREFIX, yystate, yytable[yyn]);
#endif
        if (yyssp >= yysslim && yygrowstack())
        {
            goto yyoverflow;
        }
        *++yyssp = yystate = yytable[yyn];
        *++yyvsp = yylval;
        yychar = YYEMPTY;
        if (yyerrflag > 0)  --yyerrflag;
        goto yyloop;
    }
    if ((yyn = yyrindex[yystate]) && (yyn += yychar) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yychar)
    {
        yyn = yytable[yyn];
        goto yyreduce;
    }
    if (yyerrflag) goto yyinrecovery;

    yyerror("syntax error");

#ifdef lint
    goto yyerrlab;
#endif

yyerrlab:
    ++yynerrs;

yyinrecovery:
    if (yyerrflag < 3)
    {
        yyerrflag = 3;
        for (;;)
        {
            if ((yyn = yysindex[*yyssp]) && (yyn += YYERRCODE) >= 0 &&
                    yyn <= YYTABLESIZE && yycheck[yyn] == YYERRCODE)
            {
#if YYDEBUG
                if (yydebug)
                    printf("%sdebug: state %d, error recovery shifting\
 to state %d\n", YYPREFIX, *yyssp, yytable[yyn]);
#endif
                if (yyssp >= yysslim && yygrowstack())
                {
                    goto yyoverflow;
                }
                *++yyssp = yystate = yytable[yyn];
                *++yyvsp = yylval;
                goto yyloop;
            }
            else
            {
#if YYDEBUG
                if (yydebug)
                    printf("%sdebug: error recovery discarding state %d\n",
                            YYPREFIX, *yyssp);
#endif
                if (yyssp <= yyss) goto yyabort;
                --yyssp;
                --yyvsp;
            }
        }
    }
    else
    {
        if (yychar == 0) goto yyabort;
#if YYDEBUG
        if (yydebug)
        {
            yys = 0;
            if (yychar <= YYMAXTOKEN) yys = yyname[yychar];
            if (!yys) yys = "illegal-symbol";
            printf("%sdebug: state %d, error recovery discards token %d (%s)\n",
                    YYPREFIX, yystate, yychar, yys);
        }
#endif
        yychar = YYEMPTY;
        goto yyloop;
    }

yyreduce:
#if YYDEBUG
    if (yydebug)
        printf("%sdebug: state %d, reducing by rule %d (%s)\n",
                YYPREFIX, yystate, yyn, yyrule[yyn]);
#endif
    yym = yylen[yyn];
    if (yym)
        yyval = yyvsp[1-yym];
    else
        memset(&yyval, 0, sizeof yyval);
    switch (yyn)
    {
case 1:
#line 111 "grammar.bison"
{parser_result = yyvsp[0].decl; return 0; }
break;
case 2:
#line 114 "grammar.bison"
{

	      yyval.decl = yyvsp[-1].decl;
	      yyvsp[-1].decl->next = yyvsp[0].decl;	
	    }
break;
case 3:
#line 120 "grammar.bison"
{yyval.decl = 0;}
break;
case 4:
#line 124 "grammar.bison"
{yyval.decl = decl_create(yyvsp[-5].c,yyvsp[-3].type,yyvsp[-1].expr,0,0);}
break;
case 5:
#line 126 "grammar.bison"
{yyval.decl = decl_create(yyvsp[-8].c,type_create(TYPE_ARRAY,0,yyvsp[-3].type,0),yyvsp[-1].expr,0,0);}
break;
case 6:
#line 128 "grammar.bison"
{yyval.decl = decl_create(yyvsp[-3].c,yyvsp[-1].type,0,0,0);}
break;
case 7:
#line 130 "grammar.bison"
{yyval.decl = decl_create(yyvsp[-6].c,yyvsp[-4].type,0,yyvsp[-1].stmt,0);}
break;
case 8:
#line 134 "grammar.bison"
{yyval.type = type_create(TYPE_STRING,0,0,0);}
break;
case 9:
#line 136 "grammar.bison"
{yyval.type = type_create(TYPE_INTEGER,0,0,0);}
break;
case 10:
#line 138 "grammar.bison"
{yyval.type = type_create(TYPE_CHARACTER,0,0,0);}
break;
case 11:
#line 140 "grammar.bison"
{yyval.type = type_create(TYPE_BOOLEAN,0,0,0);}
break;
case 12:
#line 142 "grammar.bison"
{yyval.type = type_create(TYPE_ARRAY,0,yyvsp[0].type,yyvsp[-2].expr);}
break;
case 13:
#line 145 "grammar.bison"
{yyval.type = type_create(TYPE_FUNCTION,yyvsp[-1].param_list,yyvsp[-3].type,0);}
break;
case 14:
#line 147 "grammar.bison"
{yyval.type = type_create(TYPE_VOID,0,0,0);}
break;
case 15:
#line 152 "grammar.bison"
{yyval.type = type_create(TYPE_STRING,0,0,0);}
break;
case 16:
#line 154 "grammar.bison"
{yyval.type = type_create(TYPE_INTEGER,0,0,0);}
break;
case 17:
#line 156 "grammar.bison"
{yyval.type = type_create(TYPE_CHARACTER,0,0,0);}
break;
case 18:
#line 158 "grammar.bison"
{yyval.type = type_create(TYPE_BOOLEAN,0,0,0);}
break;
case 19:
#line 160 "grammar.bison"
{yyval.type = type_create(TYPE_ARRAY,0,yyvsp[0].type,yyvsp[-2].expr);}
break;
case 20:
#line 162 "grammar.bison"
{yyval.type = type_create(TYPE_FUNCTION,yyvsp[-1].param_list,yyvsp[-3].type,0);}
break;
case 21:
#line 164 "grammar.bison"
{yyval.type = type_create(TYPE_VOID,0,0,0);}
break;
case 22:
#line 169 "grammar.bison"
{yyval.param_list = 0;}
break;
case 23:
#line 171 "grammar.bison"
{yyval.param_list = yyvsp[0].param_list;}
break;
case 24:
#line 175 "grammar.bison"
{yyval.param_list = param_list_create(yyvsp[-2].c,yyvsp[0].type,0);}
break;
case 25:
#line 177 "grammar.bison"
{yyval.param_list = yyvsp[0].param_list;}
break;
case 26:
#line 181 "grammar.bison"
{yyval.param_list = param_list_create(yyvsp[-4].c,yyvsp[-2].type,yyvsp[0].param_list);}
break;
case 27:
#line 185 "grammar.bison"
{yyval.expr = 0;}
break;
case 28:
#line 187 "grammar.bison"
{yyval.expr = yyvsp[0].expr;}
break;
case 29:
#line 192 "grammar.bison"
{yyval.expr = yyvsp[0].expr;}
break;
case 30:
#line 197 "grammar.bison"
{yyval.expr = expr_create(EXPR_EXPR_LIST,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 31:
#line 199 "grammar.bison"
{yyval.expr = yyvsp[0].expr;}
break;
case 32:
#line 203 "grammar.bison"
{
	char *c;
	c = strdup(yytext);
	yyval.c = c;}
break;
case 33:
#line 210 "grammar.bison"
{yyval.stmt = stmt_create(STMT_DECL,yyvsp[0].decl,0,0,0,0,0,0);}
break;
case 34:
#line 212 "grammar.bison"
{yyval.stmt = stmt_create(STMT_EXPR,0,0,yyvsp[-1].expr,0,0,0,0);}
break;
case 35:
#line 214 "grammar.bison"
{yyval.stmt = stmt_create(STMT_FOR,0,yyvsp[-6].expr,yyvsp[-4].expr,yyvsp[-2].expr,yyvsp[0].stmt,0,0);}
break;
case 36:
#line 216 "grammar.bison"
{yyval.stmt = stmt_create(STMT_BLOCK,0,0,0,0,yyvsp[-1].stmt,0,0);}
break;
case 37:
#line 218 "grammar.bison"
{yyval.stmt = stmt_create(STMT_IF_ELSE,0,0,yyvsp[-4].expr,0,yyvsp[-2].stmt,yyvsp[0].stmt,0);}
break;
case 38:
#line 220 "grammar.bison"
{yyval.stmt = stmt_create(STMT_IF_ELSE,0,0,yyvsp[-2].expr,0,yyvsp[0].stmt,0,0);}
break;
case 39:
#line 222 "grammar.bison"
{yyval.stmt = stmt_create(STMT_RETURN,0,0,yyvsp[-1].expr,0,0,0,0);}
break;
case 40:
#line 224 "grammar.bison"
{yyval.stmt = stmt_create(STMT_PRINT,0,0,yyvsp[-1].expr,0,0,0,0);}
break;
case 41:
#line 228 "grammar.bison"
{yyval.stmt = stmt_create(STMT_IF_ELSE,0,0,yyvsp[-4].expr,0,yyvsp[-2].stmt,yyvsp[0].stmt,0);}
break;
case 42:
#line 230 "grammar.bison"
{yyval.stmt = stmt_create(STMT_RETURN,0,0,yyvsp[-1].expr,0,0,0,0);}
break;
case 43:
#line 232 "grammar.bison"
{yyval.stmt = stmt_create(STMT_PRINT,0,0,yyvsp[-1].expr,0,0,0,0);}
break;
case 44:
#line 234 "grammar.bison"
{yyval.stmt = stmt_create(STMT_BLOCK,0,0,0,0,yyvsp[-1].stmt,0,0);}
break;
case 45:
#line 236 "grammar.bison"
{yyval.stmt = stmt_create(STMT_EXPR,0,0,yyvsp[-1].expr,0,0,0,0);}
break;
case 46:
#line 238 "grammar.bison"
{yyval.stmt = stmt_create(STMT_DECL,yyvsp[0].decl,0,0,0,0,0,0);}
break;
case 47:
#line 240 "grammar.bison"
{yyval.stmt = stmt_create(STMT_FOR,0,yyvsp[-6].expr,yyvsp[-4].expr,yyvsp[-2].expr,yyvsp[0].stmt,0,0);}
break;
case 48:
#line 243 "grammar.bison"
{yyval.stmt = 0;}
break;
case 49:
#line 245 "grammar.bison"
{yyval.stmt = yyvsp[0].stmt;}
break;
case 50:
#line 249 "grammar.bison"
{yyval.stmt = yyvsp[0].stmt;}
break;
case 51:
#line 251 "grammar.bison"
{yyval.stmt = yyvsp[0].stmt;}
break;
case 52:
#line 255 "grammar.bison"
{yyval.stmt = yyvsp[-1].stmt;
	      yyvsp[-1].stmt->next = yyvsp[0].stmt; }
break;
case 53:
#line 260 "grammar.bison"
{yyval.expr = 0;}
break;
case 54:
#line 262 "grammar.bison"
{yyval.expr = yyvsp[0].expr;}
break;
case 55:
#line 269 "grammar.bison"
{yyval.expr = yyvsp[0].expr;}
break;
case 56:
#line 271 "grammar.bison"
{yyval.expr = expr_create(EXPR_ASSIGN,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 57:
#line 276 "grammar.bison"
{yyval.expr = expr_create(EXPR_OR,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 58:
#line 278 "grammar.bison"
{yyval.expr = yyvsp[0].expr;}
break;
case 59:
#line 282 "grammar.bison"
{yyval.expr = expr_create(EXPR_AND,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 60:
#line 284 "grammar.bison"
{yyval.expr = yyvsp[0].expr;}
break;
case 61:
#line 289 "grammar.bison"
{yyval.expr = expr_create(EXPR_GE,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 62:
#line 291 "grammar.bison"
{yyval.expr = expr_create(EXPR_GT,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 63:
#line 293 "grammar.bison"
{yyval.expr = expr_create(EXPR_LE,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 64:
#line 295 "grammar.bison"
{yyval.expr = expr_create(EXPR_LT,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 65:
#line 297 "grammar.bison"
{yyval.expr = expr_create(EXPR_NE,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 66:
#line 299 "grammar.bison"
{yyval.expr = expr_create(EXPR_EQ,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 67:
#line 301 "grammar.bison"
{yyval.expr = yyvsp[0].expr;}
break;
case 68:
#line 305 "grammar.bison"
{yyval.expr = expr_create(EXPR_ADD,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 69:
#line 307 "grammar.bison"
{yyval.expr = expr_create(EXPR_SUB,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 70:
#line 309 "grammar.bison"
{yyval.expr = yyvsp[0].expr;}
break;
case 71:
#line 313 "grammar.bison"
{yyval.expr = expr_create(EXPR_MULT,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 72:
#line 315 "grammar.bison"
{yyval.expr = expr_create(EXPR_DIV,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 73:
#line 317 "grammar.bison"
{yyval.expr = expr_create(EXPR_MOD,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 74:
#line 319 "grammar.bison"
{yyval.expr = yyvsp[0].expr;}
break;
case 75:
#line 323 "grammar.bison"
{yyval.expr = expr_create(EXPR_EXPONENTIATION,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 76:
#line 325 "grammar.bison"
{yyval.expr = yyvsp[0].expr;}
break;
case 77:
#line 329 "grammar.bison"
{yyval.expr = expr_create(EXPR_UNARY_NEGATION,0,yyvsp[0].expr);}
break;
case 78:
#line 331 "grammar.bison"
{yyval.expr = expr_create(EXPR_MINUS,0,yyvsp[0].expr);}
break;
case 79:
#line 333 "grammar.bison"
{yyval.expr = yyvsp[0].expr;}
break;
case 80:
#line 337 "grammar.bison"
{yyval.expr = expr_create(EXPR_INCREMENT,yyvsp[-1].expr,0);}
break;
case 81:
#line 339 "grammar.bison"
{yyval.expr = expr_create(EXPR_DECREMENT,yyvsp[-1].expr,0);}
break;
case 82:
#line 341 "grammar.bison"
{yyval.expr = yyvsp[0].expr;}
break;
case 83:
#line 343 "grammar.bison"
{yyval.expr = yyvsp[0].expr;}
break;
case 84:
#line 345 "grammar.bison"
{yyval.expr = expr_create(EXPR_OPPAR,0,yyvsp[-1].expr);}
break;
case 85:
#line 348 "grammar.bison"
{yyval.expr = expr_create_name(yyvsp[0].c);}
break;
case 86:
#line 350 "grammar.bison"
{yyval.expr = expr_create(EXPR_ARRAY_IDENT,expr_create_name(yyvsp[-4].c),expr_create(EXPR_ARRAY_ELEMENT,yyvsp[-2].expr,yyvsp[0].expr));}
break;
case 87:
#line 352 "grammar.bison"
{yyval.expr = expr_create(EXPR_FUNC,expr_create_name(yyvsp[-3].c),yyvsp[-1].expr);}
break;
case 88:
#line 354 "grammar.bison"
{yyval.expr = expr_create_integer_literal(atoi(strdup(yytext)));}
break;
case 89:
#line 356 "grammar.bison"
{yyval.expr = expr_create_string_literal(strdup(yytext));}
break;
case 90:
#line 358 "grammar.bison"
{yyval.expr = expr_create_character_literal(strdup(yytext));}
break;
case 91:
#line 360 "grammar.bison"
{yyval.expr = expr_create_boolean_literal(1);}
break;
case 92:
#line 362 "grammar.bison"
{yyval.expr = expr_create_boolean_literal(0);}
break;
case 93:
#line 364 "grammar.bison"
{yyval.expr = expr_create(EXPR_ARRAY_LIST,0,yyvsp[-1].expr);}
break;
case 94:
#line 368 "grammar.bison"
{yyval.expr = expr_create(EXPR_ARRAY_ELEMENT,yyvsp[-2].expr,yyvsp[0].expr);}
break;
case 95:
#line 369 "grammar.bison"
{yyval.expr = 0;}
break;
#line 1147 "parser.tab.c"
    }
    yyssp -= yym;
    yystate = *yyssp;
    yyvsp -= yym;
    yym = yylhs[yyn];
    if (yystate == 0 && yym == 0)
    {
#if YYDEBUG
        if (yydebug)
            printf("%sdebug: after reduction, shifting from state 0 to\
 state %d\n", YYPREFIX, YYFINAL);
#endif
        yystate = YYFINAL;
        *++yyssp = YYFINAL;
        *++yyvsp = yyval;
        if (yychar < 0)
        {
            if ((yychar = yylex()) < 0) yychar = 0;
#if YYDEBUG
            if (yydebug)
            {
                yys = 0;
                if (yychar <= YYMAXTOKEN) yys = yyname[yychar];
                if (!yys) yys = "illegal-symbol";
                printf("%sdebug: state %d, reading %d (%s)\n",
                        YYPREFIX, YYFINAL, yychar, yys);
            }
#endif
        }
        if (yychar == 0) goto yyaccept;
        goto yyloop;
    }
    if ((yyn = yygindex[yym]) && (yyn += yystate) >= 0 &&
            yyn <= YYTABLESIZE && yycheck[yyn] == yystate)
        yystate = yytable[yyn];
    else
        yystate = yydgoto[yym];
#if YYDEBUG
    if (yydebug)
        printf("%sdebug: after reduction, shifting from state %d \
to state %d\n", YYPREFIX, *yyssp, yystate);
#endif
    if (yyssp >= yysslim && yygrowstack())
    {
        goto yyoverflow;
    }
    *++yyssp = yystate;
    *++yyvsp = yyval;
    goto yyloop;

yyoverflow:
    yyerror("yacc stack overflow");

yyabort:
    return (1);

yyaccept:
    return (0);
}
